## Pandas
Es una biblioteca de código abierto para Python que actúa como una potente hoja de cálculo virtual, diseñada específicamente para el análisis y la manipulación de datos. Su herramienta principal es el DataFrame, una estructura en forma de tabla con filas y columnas que permite importar fácilmente archivos externos (como Excel, CSV o bases de datos SQL) para procesar millones de registros en segundos. Los programadores y científicos de datos la utilizan como su herramienta principal para limpiar datos desordenados, filtrar información específica, rellenar valores faltantes y agrupar estadísticas, transformando datos crudos en información estructurada y lista para tomar decisiones o crear gráficos.

In [ ]:
# ==========================================
# 1. IMPORTAR LIBRERÍAS
# ==========================================

import pandas as pd
import numpy as np 


# ==========================================
# 2. CARGAR EL ARCHIVO CSV
# ==========================================

df = pd.read_csv("dataset_ventas.csv")


# ==========================================
# 3. MOSTRAR LAS PRIMERAS 5 FILAS
# ==========================================

print("Primeras 5 filas:")
display(df.head())


# ==========================================
# 4. MOSTRAR LAS ÚLTIMAS 5 FILAS
# ==========================================

print("Últimas 5 filas:")
display(df.tail())


# ==========================================
# 5. MOSTRAR 5 FILAS ALEATORIAS
# ==========================================

print("5 filas aleatorias:")
display(df.sample(n=5))


# ==========================================
# 6. INFORMACIÓN GENERAL DEL DATAFRAME
# ==========================================

print("Información general:")
df.info()


# ==========================================
# 7. ESTADÍSTICAS DESCRIPTIVAS
# ==========================================

print("Estadísticas descriptivas:")
display(df.describe())


# ==========================================
# 8. CANTIDAD DE FILAS Y COLUMNAS
# ==========================================

print("Cantidad de filas y columnas:")
print(df.shape)


# ==========================================
# 9. NOMBRES DE LAS COLUMNAS
# ==========================================

print("Nombres de las columnas:")
print(df.columns.tolist())


# ==========================================
# 10. VALORES NULOS
# ==========================================

print("Valores nulos por columna:")
print(df.isnull().sum())


# ==========================================
# 11. TIPOS DE DATOS
# ==========================================

print("Tipos de datos:")
print(df.dtypes)

Primeras 5 filas:

,fecha,ciudad,categoria,producto,cantidad,precio_unitario,total_venta
0,2025-11-24,Medellín,Tecnología,Monitor,8,60513,484104
1,2025-03-13,Medellín,Papelería,Cuaderno,19,112604,2139476
2,2025-01-17,Medellín,Tecnología,Teclado,8,134475,1075800
3,2025-11-05,Medellín,Papelería,Lapicero,18,111974,2015532
4,2025-04-23,Barranquilla,Papelería,Marcador,1,200916,200916

Últimas 5 filas:

,fecha,ciudad,categoria,producto,cantidad,precio_unitario,total_venta
995,2025-01-18,Bogotá,Alimentos,Arroz,17,176589,3002013
996,2025-04-17,Barranquilla,Alimentos,Café,11,43579,479369
997,2025-11-19,Medellín,Papelería,Resma,4,68404,273616
998,2025-09-04,Cali,Hogar,Lámpara,2,228402,456804
999,2025-12-08,Bogotá,Tecnología,Teclado,14,87069,1218966

5 filas aleatorias:

,fecha,ciudad,categoria,producto,cantidad,precio_unitario,total_venta
441,2025-12-11,Apartadó,Alimentos,Leche,13,217838,2831894
341,2025-04-06,Barranquilla,Papelería,Carpeta,18,32870,591660
223,2025-01-26,Cali,Hogar,Mesa,19,55793,1060067
473,2025-01-04,Barranquilla,Hogar,Mesa,3,187380,562140
304,2025-09-20,Bogotá,Alimentos,Arroz,8,216093,1728744

Información general:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1000 non-null   str
 1   ciudad           1000 non-null   str
 2   categoria        1000 non-null   str
 3   producto         1000 non-null   str
 4   cantidad         1000 non-null   int64
 5   precio_unitario  1000 non-null   int64
 6   total_venta      1000 non-null   int64
dtypes: int64(3), str(4)
memory usage: 54.8 KB
Estadísticas descriptivas:

          cantidad  precio_unitario   total_venta
count  1000.000000      1000.000000  1.000000e+03
mean     10.953000    124923.302000  1.353003e+06
std       5.860302     70124.115622  1.120452e+06
min       1.000000      2284.000000  5.098000e+03
25%       6.000000     66371.500000  4.329180e+05
50%      11.000000    123593.500000  1.050503e+06
75%      16.000000    183019.250000  2.018011e+06
max      20.000000    249542.000000  4.866180e+06

Cantidad de filas y columnas:
(1000, 7)
Nombres de las columnas:
['fecha', 'ciudad', 'categoria', 'producto', 'cantidad', 'precio_unitario', 'total_venta']
Valores nulos por columna:
fecha              0
ciudad             0
categoria          0
producto           0
cantidad           0
precio_unitario    0
total_venta        0
dtype: int64
Tipos de datos:
fecha                str
ciudad               str
categoria            str
producto             str
cantidad           int64
precio_unitario    int64
total_venta        int64
dtype: object

Manejo de Valores Faltantes y duplicados